/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.luca.batch.factory.model.amex;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AmexAvroRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5662051854401216001L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AmexAvroRecord\",\"namespace\":\"it.luca.batch.factory.model.amex\",\"fields\":[{\"name\":\"tipo_record\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"progressivo_record\",\"type\":[\"int\",\"null\"]},{\"name\":\"ndg_banca\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"data_inserimento_richiesta_carta\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"data_approvazione_richiesta_carta\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"descrizione_prodotto\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"tipo_carta\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"product_type_code\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"totale_speso_mensile_carta_segno\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"totale_speso_mensile_carta_anno_segno\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"quota_annua_primo_anno_mese_segno\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"quota_annua_primo_anno_anno_segno\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"lending_indicator\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"revolve_indicator\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AmexAvroRecord> ENCODER =
      new BinaryMessageEncoder<AmexAvroRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AmexAvroRecord> DECODER =
      new BinaryMessageDecoder<AmexAvroRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AmexAvroRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AmexAvroRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AmexAvroRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AmexAvroRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AmexAvroRecord from a ByteBuffer. */
  public static AmexAvroRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String tipo_record;
   private java.lang.Integer progressivo_record;
   private java.lang.String ndg_banca;
   private java.lang.String data_inserimento_richiesta_carta;
   private java.lang.String data_approvazione_richiesta_carta;
   private java.lang.String descrizione_prodotto;
   private java.lang.String tipo_carta;
   private java.lang.String product_type_code;
   private java.lang.String totale_speso_mensile_carta_segno;
   private java.lang.String totale_speso_mensile_carta_anno_segno;
   private java.lang.String quota_annua_primo_anno_mese_segno;
   private java.lang.String quota_annua_primo_anno_anno_segno;
   private java.lang.String lending_indicator;
   private java.lang.String revolve_indicator;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AmexAvroRecord() {}

  /**
   * All-args constructor.
   * @param tipo_record The new value for tipo_record
   * @param progressivo_record The new value for progressivo_record
   * @param ndg_banca The new value for ndg_banca
   * @param data_inserimento_richiesta_carta The new value for data_inserimento_richiesta_carta
   * @param data_approvazione_richiesta_carta The new value for data_approvazione_richiesta_carta
   * @param descrizione_prodotto The new value for descrizione_prodotto
   * @param tipo_carta The new value for tipo_carta
   * @param product_type_code The new value for product_type_code
   * @param totale_speso_mensile_carta_segno The new value for totale_speso_mensile_carta_segno
   * @param totale_speso_mensile_carta_anno_segno The new value for totale_speso_mensile_carta_anno_segno
   * @param quota_annua_primo_anno_mese_segno The new value for quota_annua_primo_anno_mese_segno
   * @param quota_annua_primo_anno_anno_segno The new value for quota_annua_primo_anno_anno_segno
   * @param lending_indicator The new value for lending_indicator
   * @param revolve_indicator The new value for revolve_indicator
   */
  public AmexAvroRecord(java.lang.String tipo_record, java.lang.Integer progressivo_record, java.lang.String ndg_banca, java.lang.String data_inserimento_richiesta_carta, java.lang.String data_approvazione_richiesta_carta, java.lang.String descrizione_prodotto, java.lang.String tipo_carta, java.lang.String product_type_code, java.lang.String totale_speso_mensile_carta_segno, java.lang.String totale_speso_mensile_carta_anno_segno, java.lang.String quota_annua_primo_anno_mese_segno, java.lang.String quota_annua_primo_anno_anno_segno, java.lang.String lending_indicator, java.lang.String revolve_indicator) {
    this.tipo_record = tipo_record;
    this.progressivo_record = progressivo_record;
    this.ndg_banca = ndg_banca;
    this.data_inserimento_richiesta_carta = data_inserimento_richiesta_carta;
    this.data_approvazione_richiesta_carta = data_approvazione_richiesta_carta;
    this.descrizione_prodotto = descrizione_prodotto;
    this.tipo_carta = tipo_carta;
    this.product_type_code = product_type_code;
    this.totale_speso_mensile_carta_segno = totale_speso_mensile_carta_segno;
    this.totale_speso_mensile_carta_anno_segno = totale_speso_mensile_carta_anno_segno;
    this.quota_annua_primo_anno_mese_segno = quota_annua_primo_anno_mese_segno;
    this.quota_annua_primo_anno_anno_segno = quota_annua_primo_anno_anno_segno;
    this.lending_indicator = lending_indicator;
    this.revolve_indicator = revolve_indicator;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tipo_record;
    case 1: return progressivo_record;
    case 2: return ndg_banca;
    case 3: return data_inserimento_richiesta_carta;
    case 4: return data_approvazione_richiesta_carta;
    case 5: return descrizione_prodotto;
    case 6: return tipo_carta;
    case 7: return product_type_code;
    case 8: return totale_speso_mensile_carta_segno;
    case 9: return totale_speso_mensile_carta_anno_segno;
    case 10: return quota_annua_primo_anno_mese_segno;
    case 11: return quota_annua_primo_anno_anno_segno;
    case 12: return lending_indicator;
    case 13: return revolve_indicator;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tipo_record = (java.lang.String)value$; break;
    case 1: progressivo_record = (java.lang.Integer)value$; break;
    case 2: ndg_banca = (java.lang.String)value$; break;
    case 3: data_inserimento_richiesta_carta = (java.lang.String)value$; break;
    case 4: data_approvazione_richiesta_carta = (java.lang.String)value$; break;
    case 5: descrizione_prodotto = (java.lang.String)value$; break;
    case 6: tipo_carta = (java.lang.String)value$; break;
    case 7: product_type_code = (java.lang.String)value$; break;
    case 8: totale_speso_mensile_carta_segno = (java.lang.String)value$; break;
    case 9: totale_speso_mensile_carta_anno_segno = (java.lang.String)value$; break;
    case 10: quota_annua_primo_anno_mese_segno = (java.lang.String)value$; break;
    case 11: quota_annua_primo_anno_anno_segno = (java.lang.String)value$; break;
    case 12: lending_indicator = (java.lang.String)value$; break;
    case 13: revolve_indicator = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tipo_record' field.
   * @return The value of the 'tipo_record' field.
   */
  public java.lang.String getTipoRecord() {
    return tipo_record;
  }

  /**
   * Sets the value of the 'tipo_record' field.
   * @param value the value to set.
   */
  public void setTipoRecord(java.lang.String value) {
    this.tipo_record = value;
  }

  /**
   * Gets the value of the 'progressivo_record' field.
   * @return The value of the 'progressivo_record' field.
   */
  public java.lang.Integer getProgressivoRecord() {
    return progressivo_record;
  }

  /**
   * Sets the value of the 'progressivo_record' field.
   * @param value the value to set.
   */
  public void setProgressivoRecord(java.lang.Integer value) {
    this.progressivo_record = value;
  }

  /**
   * Gets the value of the 'ndg_banca' field.
   * @return The value of the 'ndg_banca' field.
   */
  public java.lang.String getNdgBanca() {
    return ndg_banca;
  }

  /**
   * Sets the value of the 'ndg_banca' field.
   * @param value the value to set.
   */
  public void setNdgBanca(java.lang.String value) {
    this.ndg_banca = value;
  }

  /**
   * Gets the value of the 'data_inserimento_richiesta_carta' field.
   * @return The value of the 'data_inserimento_richiesta_carta' field.
   */
  public java.lang.String getDataInserimentoRichiestaCarta() {
    return data_inserimento_richiesta_carta;
  }

  /**
   * Sets the value of the 'data_inserimento_richiesta_carta' field.
   * @param value the value to set.
   */
  public void setDataInserimentoRichiestaCarta(java.lang.String value) {
    this.data_inserimento_richiesta_carta = value;
  }

  /**
   * Gets the value of the 'data_approvazione_richiesta_carta' field.
   * @return The value of the 'data_approvazione_richiesta_carta' field.
   */
  public java.lang.String getDataApprovazioneRichiestaCarta() {
    return data_approvazione_richiesta_carta;
  }

  /**
   * Sets the value of the 'data_approvazione_richiesta_carta' field.
   * @param value the value to set.
   */
  public void setDataApprovazioneRichiestaCarta(java.lang.String value) {
    this.data_approvazione_richiesta_carta = value;
  }

  /**
   * Gets the value of the 'descrizione_prodotto' field.
   * @return The value of the 'descrizione_prodotto' field.
   */
  public java.lang.String getDescrizioneProdotto() {
    return descrizione_prodotto;
  }

  /**
   * Sets the value of the 'descrizione_prodotto' field.
   * @param value the value to set.
   */
  public void setDescrizioneProdotto(java.lang.String value) {
    this.descrizione_prodotto = value;
  }

  /**
   * Gets the value of the 'tipo_carta' field.
   * @return The value of the 'tipo_carta' field.
   */
  public java.lang.String getTipoCarta() {
    return tipo_carta;
  }

  /**
   * Sets the value of the 'tipo_carta' field.
   * @param value the value to set.
   */
  public void setTipoCarta(java.lang.String value) {
    this.tipo_carta = value;
  }

  /**
   * Gets the value of the 'product_type_code' field.
   * @return The value of the 'product_type_code' field.
   */
  public java.lang.String getProductTypeCode() {
    return product_type_code;
  }

  /**
   * Sets the value of the 'product_type_code' field.
   * @param value the value to set.
   */
  public void setProductTypeCode(java.lang.String value) {
    this.product_type_code = value;
  }

  /**
   * Gets the value of the 'totale_speso_mensile_carta_segno' field.
   * @return The value of the 'totale_speso_mensile_carta_segno' field.
   */
  public java.lang.String getTotaleSpesoMensileCartaSegno() {
    return totale_speso_mensile_carta_segno;
  }

  /**
   * Sets the value of the 'totale_speso_mensile_carta_segno' field.
   * @param value the value to set.
   */
  public void setTotaleSpesoMensileCartaSegno(java.lang.String value) {
    this.totale_speso_mensile_carta_segno = value;
  }

  /**
   * Gets the value of the 'totale_speso_mensile_carta_anno_segno' field.
   * @return The value of the 'totale_speso_mensile_carta_anno_segno' field.
   */
  public java.lang.String getTotaleSpesoMensileCartaAnnoSegno() {
    return totale_speso_mensile_carta_anno_segno;
  }

  /**
   * Sets the value of the 'totale_speso_mensile_carta_anno_segno' field.
   * @param value the value to set.
   */
  public void setTotaleSpesoMensileCartaAnnoSegno(java.lang.String value) {
    this.totale_speso_mensile_carta_anno_segno = value;
  }

  /**
   * Gets the value of the 'quota_annua_primo_anno_mese_segno' field.
   * @return The value of the 'quota_annua_primo_anno_mese_segno' field.
   */
  public java.lang.String getQuotaAnnuaPrimoAnnoMeseSegno() {
    return quota_annua_primo_anno_mese_segno;
  }

  /**
   * Sets the value of the 'quota_annua_primo_anno_mese_segno' field.
   * @param value the value to set.
   */
  public void setQuotaAnnuaPrimoAnnoMeseSegno(java.lang.String value) {
    this.quota_annua_primo_anno_mese_segno = value;
  }

  /**
   * Gets the value of the 'quota_annua_primo_anno_anno_segno' field.
   * @return The value of the 'quota_annua_primo_anno_anno_segno' field.
   */
  public java.lang.String getQuotaAnnuaPrimoAnnoAnnoSegno() {
    return quota_annua_primo_anno_anno_segno;
  }

  /**
   * Sets the value of the 'quota_annua_primo_anno_anno_segno' field.
   * @param value the value to set.
   */
  public void setQuotaAnnuaPrimoAnnoAnnoSegno(java.lang.String value) {
    this.quota_annua_primo_anno_anno_segno = value;
  }

  /**
   * Gets the value of the 'lending_indicator' field.
   * @return The value of the 'lending_indicator' field.
   */
  public java.lang.String getLendingIndicator() {
    return lending_indicator;
  }

  /**
   * Sets the value of the 'lending_indicator' field.
   * @param value the value to set.
   */
  public void setLendingIndicator(java.lang.String value) {
    this.lending_indicator = value;
  }

  /**
   * Gets the value of the 'revolve_indicator' field.
   * @return The value of the 'revolve_indicator' field.
   */
  public java.lang.String getRevolveIndicator() {
    return revolve_indicator;
  }

  /**
   * Sets the value of the 'revolve_indicator' field.
   * @param value the value to set.
   */
  public void setRevolveIndicator(java.lang.String value) {
    this.revolve_indicator = value;
  }

  /**
   * Creates a new AmexAvroRecord RecordBuilder.
   * @return A new AmexAvroRecord RecordBuilder
   */
  public static it.luca.batch.factory.model.amex.AmexAvroRecord.Builder newBuilder() {
    return new it.luca.batch.factory.model.amex.AmexAvroRecord.Builder();
  }

  /**
   * Creates a new AmexAvroRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AmexAvroRecord RecordBuilder
   */
  public static it.luca.batch.factory.model.amex.AmexAvroRecord.Builder newBuilder(it.luca.batch.factory.model.amex.AmexAvroRecord.Builder other) {
    if (other == null) {
      return new it.luca.batch.factory.model.amex.AmexAvroRecord.Builder();
    } else {
      return new it.luca.batch.factory.model.amex.AmexAvroRecord.Builder(other);
    }
  }

  /**
   * Creates a new AmexAvroRecord RecordBuilder by copying an existing AmexAvroRecord instance.
   * @param other The existing instance to copy.
   * @return A new AmexAvroRecord RecordBuilder
   */
  public static it.luca.batch.factory.model.amex.AmexAvroRecord.Builder newBuilder(it.luca.batch.factory.model.amex.AmexAvroRecord other) {
    if (other == null) {
      return new it.luca.batch.factory.model.amex.AmexAvroRecord.Builder();
    } else {
      return new it.luca.batch.factory.model.amex.AmexAvroRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for AmexAvroRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AmexAvroRecord>
    implements org.apache.avro.data.RecordBuilder<AmexAvroRecord> {

    private java.lang.String tipo_record;
    private java.lang.Integer progressivo_record;
    private java.lang.String ndg_banca;
    private java.lang.String data_inserimento_richiesta_carta;
    private java.lang.String data_approvazione_richiesta_carta;
    private java.lang.String descrizione_prodotto;
    private java.lang.String tipo_carta;
    private java.lang.String product_type_code;
    private java.lang.String totale_speso_mensile_carta_segno;
    private java.lang.String totale_speso_mensile_carta_anno_segno;
    private java.lang.String quota_annua_primo_anno_mese_segno;
    private java.lang.String quota_annua_primo_anno_anno_segno;
    private java.lang.String lending_indicator;
    private java.lang.String revolve_indicator;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.luca.batch.factory.model.amex.AmexAvroRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tipo_record)) {
        this.tipo_record = data().deepCopy(fields()[0].schema(), other.tipo_record);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.progressivo_record)) {
        this.progressivo_record = data().deepCopy(fields()[1].schema(), other.progressivo_record);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ndg_banca)) {
        this.ndg_banca = data().deepCopy(fields()[2].schema(), other.ndg_banca);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.data_inserimento_richiesta_carta)) {
        this.data_inserimento_richiesta_carta = data().deepCopy(fields()[3].schema(), other.data_inserimento_richiesta_carta);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.data_approvazione_richiesta_carta)) {
        this.data_approvazione_richiesta_carta = data().deepCopy(fields()[4].schema(), other.data_approvazione_richiesta_carta);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.descrizione_prodotto)) {
        this.descrizione_prodotto = data().deepCopy(fields()[5].schema(), other.descrizione_prodotto);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.tipo_carta)) {
        this.tipo_carta = data().deepCopy(fields()[6].schema(), other.tipo_carta);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.product_type_code)) {
        this.product_type_code = data().deepCopy(fields()[7].schema(), other.product_type_code);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.totale_speso_mensile_carta_segno)) {
        this.totale_speso_mensile_carta_segno = data().deepCopy(fields()[8].schema(), other.totale_speso_mensile_carta_segno);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.totale_speso_mensile_carta_anno_segno)) {
        this.totale_speso_mensile_carta_anno_segno = data().deepCopy(fields()[9].schema(), other.totale_speso_mensile_carta_anno_segno);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.quota_annua_primo_anno_mese_segno)) {
        this.quota_annua_primo_anno_mese_segno = data().deepCopy(fields()[10].schema(), other.quota_annua_primo_anno_mese_segno);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.quota_annua_primo_anno_anno_segno)) {
        this.quota_annua_primo_anno_anno_segno = data().deepCopy(fields()[11].schema(), other.quota_annua_primo_anno_anno_segno);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.lending_indicator)) {
        this.lending_indicator = data().deepCopy(fields()[12].schema(), other.lending_indicator);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.revolve_indicator)) {
        this.revolve_indicator = data().deepCopy(fields()[13].schema(), other.revolve_indicator);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing AmexAvroRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(it.luca.batch.factory.model.amex.AmexAvroRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tipo_record)) {
        this.tipo_record = data().deepCopy(fields()[0].schema(), other.tipo_record);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.progressivo_record)) {
        this.progressivo_record = data().deepCopy(fields()[1].schema(), other.progressivo_record);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ndg_banca)) {
        this.ndg_banca = data().deepCopy(fields()[2].schema(), other.ndg_banca);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.data_inserimento_richiesta_carta)) {
        this.data_inserimento_richiesta_carta = data().deepCopy(fields()[3].schema(), other.data_inserimento_richiesta_carta);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.data_approvazione_richiesta_carta)) {
        this.data_approvazione_richiesta_carta = data().deepCopy(fields()[4].schema(), other.data_approvazione_richiesta_carta);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.descrizione_prodotto)) {
        this.descrizione_prodotto = data().deepCopy(fields()[5].schema(), other.descrizione_prodotto);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tipo_carta)) {
        this.tipo_carta = data().deepCopy(fields()[6].schema(), other.tipo_carta);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.product_type_code)) {
        this.product_type_code = data().deepCopy(fields()[7].schema(), other.product_type_code);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.totale_speso_mensile_carta_segno)) {
        this.totale_speso_mensile_carta_segno = data().deepCopy(fields()[8].schema(), other.totale_speso_mensile_carta_segno);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.totale_speso_mensile_carta_anno_segno)) {
        this.totale_speso_mensile_carta_anno_segno = data().deepCopy(fields()[9].schema(), other.totale_speso_mensile_carta_anno_segno);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.quota_annua_primo_anno_mese_segno)) {
        this.quota_annua_primo_anno_mese_segno = data().deepCopy(fields()[10].schema(), other.quota_annua_primo_anno_mese_segno);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.quota_annua_primo_anno_anno_segno)) {
        this.quota_annua_primo_anno_anno_segno = data().deepCopy(fields()[11].schema(), other.quota_annua_primo_anno_anno_segno);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.lending_indicator)) {
        this.lending_indicator = data().deepCopy(fields()[12].schema(), other.lending_indicator);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.revolve_indicator)) {
        this.revolve_indicator = data().deepCopy(fields()[13].schema(), other.revolve_indicator);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'tipo_record' field.
      * @return The value.
      */
    public java.lang.String getTipoRecord() {
      return tipo_record;
    }

    /**
      * Sets the value of the 'tipo_record' field.
      * @param value The value of 'tipo_record'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setTipoRecord(java.lang.String value) {
      validate(fields()[0], value);
      this.tipo_record = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo_record' field has been set.
      * @return True if the 'tipo_record' field has been set, false otherwise.
      */
    public boolean hasTipoRecord() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tipo_record' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearTipoRecord() {
      tipo_record = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'progressivo_record' field.
      * @return The value.
      */
    public java.lang.Integer getProgressivoRecord() {
      return progressivo_record;
    }

    /**
      * Sets the value of the 'progressivo_record' field.
      * @param value The value of 'progressivo_record'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setProgressivoRecord(java.lang.Integer value) {
      validate(fields()[1], value);
      this.progressivo_record = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'progressivo_record' field has been set.
      * @return True if the 'progressivo_record' field has been set, false otherwise.
      */
    public boolean hasProgressivoRecord() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'progressivo_record' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearProgressivoRecord() {
      progressivo_record = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ndg_banca' field.
      * @return The value.
      */
    public java.lang.String getNdgBanca() {
      return ndg_banca;
    }

    /**
      * Sets the value of the 'ndg_banca' field.
      * @param value The value of 'ndg_banca'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setNdgBanca(java.lang.String value) {
      validate(fields()[2], value);
      this.ndg_banca = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ndg_banca' field has been set.
      * @return True if the 'ndg_banca' field has been set, false otherwise.
      */
    public boolean hasNdgBanca() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ndg_banca' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearNdgBanca() {
      ndg_banca = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'data_inserimento_richiesta_carta' field.
      * @return The value.
      */
    public java.lang.String getDataInserimentoRichiestaCarta() {
      return data_inserimento_richiesta_carta;
    }

    /**
      * Sets the value of the 'data_inserimento_richiesta_carta' field.
      * @param value The value of 'data_inserimento_richiesta_carta'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setDataInserimentoRichiestaCarta(java.lang.String value) {
      validate(fields()[3], value);
      this.data_inserimento_richiesta_carta = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'data_inserimento_richiesta_carta' field has been set.
      * @return True if the 'data_inserimento_richiesta_carta' field has been set, false otherwise.
      */
    public boolean hasDataInserimentoRichiestaCarta() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'data_inserimento_richiesta_carta' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearDataInserimentoRichiestaCarta() {
      data_inserimento_richiesta_carta = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'data_approvazione_richiesta_carta' field.
      * @return The value.
      */
    public java.lang.String getDataApprovazioneRichiestaCarta() {
      return data_approvazione_richiesta_carta;
    }

    /**
      * Sets the value of the 'data_approvazione_richiesta_carta' field.
      * @param value The value of 'data_approvazione_richiesta_carta'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setDataApprovazioneRichiestaCarta(java.lang.String value) {
      validate(fields()[4], value);
      this.data_approvazione_richiesta_carta = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'data_approvazione_richiesta_carta' field has been set.
      * @return True if the 'data_approvazione_richiesta_carta' field has been set, false otherwise.
      */
    public boolean hasDataApprovazioneRichiestaCarta() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'data_approvazione_richiesta_carta' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearDataApprovazioneRichiestaCarta() {
      data_approvazione_richiesta_carta = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'descrizione_prodotto' field.
      * @return The value.
      */
    public java.lang.String getDescrizioneProdotto() {
      return descrizione_prodotto;
    }

    /**
      * Sets the value of the 'descrizione_prodotto' field.
      * @param value The value of 'descrizione_prodotto'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setDescrizioneProdotto(java.lang.String value) {
      validate(fields()[5], value);
      this.descrizione_prodotto = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'descrizione_prodotto' field has been set.
      * @return True if the 'descrizione_prodotto' field has been set, false otherwise.
      */
    public boolean hasDescrizioneProdotto() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'descrizione_prodotto' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearDescrizioneProdotto() {
      descrizione_prodotto = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipo_carta' field.
      * @return The value.
      */
    public java.lang.String getTipoCarta() {
      return tipo_carta;
    }

    /**
      * Sets the value of the 'tipo_carta' field.
      * @param value The value of 'tipo_carta'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setTipoCarta(java.lang.String value) {
      validate(fields()[6], value);
      this.tipo_carta = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo_carta' field has been set.
      * @return True if the 'tipo_carta' field has been set, false otherwise.
      */
    public boolean hasTipoCarta() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'tipo_carta' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearTipoCarta() {
      tipo_carta = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_type_code' field.
      * @return The value.
      */
    public java.lang.String getProductTypeCode() {
      return product_type_code;
    }

    /**
      * Sets the value of the 'product_type_code' field.
      * @param value The value of 'product_type_code'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setProductTypeCode(java.lang.String value) {
      validate(fields()[7], value);
      this.product_type_code = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'product_type_code' field has been set.
      * @return True if the 'product_type_code' field has been set, false otherwise.
      */
    public boolean hasProductTypeCode() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'product_type_code' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearProductTypeCode() {
      product_type_code = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'totale_speso_mensile_carta_segno' field.
      * @return The value.
      */
    public java.lang.String getTotaleSpesoMensileCartaSegno() {
      return totale_speso_mensile_carta_segno;
    }

    /**
      * Sets the value of the 'totale_speso_mensile_carta_segno' field.
      * @param value The value of 'totale_speso_mensile_carta_segno'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setTotaleSpesoMensileCartaSegno(java.lang.String value) {
      validate(fields()[8], value);
      this.totale_speso_mensile_carta_segno = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'totale_speso_mensile_carta_segno' field has been set.
      * @return True if the 'totale_speso_mensile_carta_segno' field has been set, false otherwise.
      */
    public boolean hasTotaleSpesoMensileCartaSegno() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'totale_speso_mensile_carta_segno' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearTotaleSpesoMensileCartaSegno() {
      totale_speso_mensile_carta_segno = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'totale_speso_mensile_carta_anno_segno' field.
      * @return The value.
      */
    public java.lang.String getTotaleSpesoMensileCartaAnnoSegno() {
      return totale_speso_mensile_carta_anno_segno;
    }

    /**
      * Sets the value of the 'totale_speso_mensile_carta_anno_segno' field.
      * @param value The value of 'totale_speso_mensile_carta_anno_segno'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setTotaleSpesoMensileCartaAnnoSegno(java.lang.String value) {
      validate(fields()[9], value);
      this.totale_speso_mensile_carta_anno_segno = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'totale_speso_mensile_carta_anno_segno' field has been set.
      * @return True if the 'totale_speso_mensile_carta_anno_segno' field has been set, false otherwise.
      */
    public boolean hasTotaleSpesoMensileCartaAnnoSegno() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'totale_speso_mensile_carta_anno_segno' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearTotaleSpesoMensileCartaAnnoSegno() {
      totale_speso_mensile_carta_anno_segno = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'quota_annua_primo_anno_mese_segno' field.
      * @return The value.
      */
    public java.lang.String getQuotaAnnuaPrimoAnnoMeseSegno() {
      return quota_annua_primo_anno_mese_segno;
    }

    /**
      * Sets the value of the 'quota_annua_primo_anno_mese_segno' field.
      * @param value The value of 'quota_annua_primo_anno_mese_segno'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setQuotaAnnuaPrimoAnnoMeseSegno(java.lang.String value) {
      validate(fields()[10], value);
      this.quota_annua_primo_anno_mese_segno = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'quota_annua_primo_anno_mese_segno' field has been set.
      * @return True if the 'quota_annua_primo_anno_mese_segno' field has been set, false otherwise.
      */
    public boolean hasQuotaAnnuaPrimoAnnoMeseSegno() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'quota_annua_primo_anno_mese_segno' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearQuotaAnnuaPrimoAnnoMeseSegno() {
      quota_annua_primo_anno_mese_segno = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'quota_annua_primo_anno_anno_segno' field.
      * @return The value.
      */
    public java.lang.String getQuotaAnnuaPrimoAnnoAnnoSegno() {
      return quota_annua_primo_anno_anno_segno;
    }

    /**
      * Sets the value of the 'quota_annua_primo_anno_anno_segno' field.
      * @param value The value of 'quota_annua_primo_anno_anno_segno'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setQuotaAnnuaPrimoAnnoAnnoSegno(java.lang.String value) {
      validate(fields()[11], value);
      this.quota_annua_primo_anno_anno_segno = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'quota_annua_primo_anno_anno_segno' field has been set.
      * @return True if the 'quota_annua_primo_anno_anno_segno' field has been set, false otherwise.
      */
    public boolean hasQuotaAnnuaPrimoAnnoAnnoSegno() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'quota_annua_primo_anno_anno_segno' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearQuotaAnnuaPrimoAnnoAnnoSegno() {
      quota_annua_primo_anno_anno_segno = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'lending_indicator' field.
      * @return The value.
      */
    public java.lang.String getLendingIndicator() {
      return lending_indicator;
    }

    /**
      * Sets the value of the 'lending_indicator' field.
      * @param value The value of 'lending_indicator'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setLendingIndicator(java.lang.String value) {
      validate(fields()[12], value);
      this.lending_indicator = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'lending_indicator' field has been set.
      * @return True if the 'lending_indicator' field has been set, false otherwise.
      */
    public boolean hasLendingIndicator() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'lending_indicator' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearLendingIndicator() {
      lending_indicator = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'revolve_indicator' field.
      * @return The value.
      */
    public java.lang.String getRevolveIndicator() {
      return revolve_indicator;
    }

    /**
      * Sets the value of the 'revolve_indicator' field.
      * @param value The value of 'revolve_indicator'.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder setRevolveIndicator(java.lang.String value) {
      validate(fields()[13], value);
      this.revolve_indicator = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'revolve_indicator' field has been set.
      * @return True if the 'revolve_indicator' field has been set, false otherwise.
      */
    public boolean hasRevolveIndicator() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'revolve_indicator' field.
      * @return This builder.
      */
    public it.luca.batch.factory.model.amex.AmexAvroRecord.Builder clearRevolveIndicator() {
      revolve_indicator = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AmexAvroRecord build() {
      try {
        AmexAvroRecord record = new AmexAvroRecord();
        record.tipo_record = fieldSetFlags()[0] ? this.tipo_record : (java.lang.String) defaultValue(fields()[0]);
        record.progressivo_record = fieldSetFlags()[1] ? this.progressivo_record : (java.lang.Integer) defaultValue(fields()[1]);
        record.ndg_banca = fieldSetFlags()[2] ? this.ndg_banca : (java.lang.String) defaultValue(fields()[2]);
        record.data_inserimento_richiesta_carta = fieldSetFlags()[3] ? this.data_inserimento_richiesta_carta : (java.lang.String) defaultValue(fields()[3]);
        record.data_approvazione_richiesta_carta = fieldSetFlags()[4] ? this.data_approvazione_richiesta_carta : (java.lang.String) defaultValue(fields()[4]);
        record.descrizione_prodotto = fieldSetFlags()[5] ? this.descrizione_prodotto : (java.lang.String) defaultValue(fields()[5]);
        record.tipo_carta = fieldSetFlags()[6] ? this.tipo_carta : (java.lang.String) defaultValue(fields()[6]);
        record.product_type_code = fieldSetFlags()[7] ? this.product_type_code : (java.lang.String) defaultValue(fields()[7]);
        record.totale_speso_mensile_carta_segno = fieldSetFlags()[8] ? this.totale_speso_mensile_carta_segno : (java.lang.String) defaultValue(fields()[8]);
        record.totale_speso_mensile_carta_anno_segno = fieldSetFlags()[9] ? this.totale_speso_mensile_carta_anno_segno : (java.lang.String) defaultValue(fields()[9]);
        record.quota_annua_primo_anno_mese_segno = fieldSetFlags()[10] ? this.quota_annua_primo_anno_mese_segno : (java.lang.String) defaultValue(fields()[10]);
        record.quota_annua_primo_anno_anno_segno = fieldSetFlags()[11] ? this.quota_annua_primo_anno_anno_segno : (java.lang.String) defaultValue(fields()[11]);
        record.lending_indicator = fieldSetFlags()[12] ? this.lending_indicator : (java.lang.String) defaultValue(fields()[12]);
        record.revolve_indicator = fieldSetFlags()[13] ? this.revolve_indicator : (java.lang.String) defaultValue(fields()[13]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AmexAvroRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<AmexAvroRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AmexAvroRecord>
    READER$ = (org.apache.avro.io.DatumReader<AmexAvroRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
