spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: @jdbc.user@
    password: @jdbc.password@
    url: @jdbc.url@
  hadoop:
    hdfs:
      uri: hdfs://quickstart-bigdata:8020
      user: osboxes
      defaultPermissions: -rwxr-xr-x

application:
  dataSources:
    -
      id: OCS_DAILY
      type: csv
      dataClass: OcsDailyRecord
      size: 1000000
      fileSystemType: HDFS
      targetPath: /user/osboxes/applications/aurora_dataload/landing/ocs_daily
      fileName: ocs_daily_yyyyMMdd.csv.gz