spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: @jdbc.user@
    password: @jdbc.password@
    url: @jdbc.url@
  flyway:
    baseline-on-migrate: true
    table: flyway_schema_history_batch_app
hadoop:
  configuration:
    uri: hdfs://quickstart-bigdata:8020
    user: osboxes
    defaultPermissions: -rwxr-xr-x
    connectionTimeoutMillis: 10000
    maxRetries: 2